### ISSUE TITLE
Auto login after registration doesn't work

### ISSUE THREAD

**Issue by erbridge** [stormpath/stormpath-express#100]
Using the following in the config:

```js
  web: {
    register: {
      enabled:    true,
      autoLogin:  true
    }
  }
```

Running off 80315b2 (while waiting for the fix for #87 to be released).

**Comment by erbridge** [comment]
Setting `autoAuthorize: true` fixes this issue.

**Comment by erbridge** [comment]
This also prevents `postRegistrationHandler` from firing.

**Comment by rdegges** [comment]
Going to close this out as this option has been renamed `autoAuthorize` in the 2.x releases. I've got a bug filed for the postregistrationhandler stuff already -- am working on that =)

**Comment by erbridge** [comment]
My mistake. I'd misread the spec on this one. `postRegistrationHandler` works fine for me with `autoAuthorize: true`.
