### ISSUE TITLE
passwordConfirm is put in the customData after registration

### ISSUE THREAD

**Issue by erbridge** [stormpath/stormpath-express#101]
Running off 80315b2 (while waiting for the fix for #87 to be released).

**Comment by rdegges** [comment]
This is fixed in #87 =) Closing it out. Will be cutting the release today.

**Comment by erbridge** [comment]
This was actually experienced while running off master after that PR was merged, so I'm not sure it is fixed.

**Comment by rdegges** [comment]
Can you try running off the latest master?

**Comment by erbridge** [comment]
Appears to be fixed on master.

**Comment by rdegges** [comment]
This has been released =)
