### ISSUE TITLE
Unable to auto expand customData

### ISSUE THREAD

**Issue by erbridge** [stormpath/stormpath-express#102]
The config contains:

```js
  expand: {
    customData: true
  }
```

Running off 80315b2 (while waiting for the fix for #87 to be released).

**Comment by bassie1995** [comment]
I seem to be having this issue as well, my config contains expandCustomData: true.

Can't test right now, however, as NPM won't install express-stormpath...

**Comment by erbridge** [comment]
I've hooked up the `stormpathLogger` to my actual logger, and I'm now seeing `Failed to authenticate the request.` (https://github.com/stormpath/stormpath-express/blob/master/lib/helpers.js#L381) in the logs, which might explain why the data isn't being fetched.

**Comment by erbridge** [comment]
Submitted a PR (#110) that fixes this for me.

**Comment by bassie1995** [comment]
This is not fixed for me. 2.0.8 Still logs the customData href instead of the information.
