### ISSUE TITLE
Issue with Social Login Google

### ISSUE THREAD

**Issue by dgisser** [stormpath/stormpath-express#118]
When I try to login via google+, I get an "Uncaught TypeError: Cannot read property 'replace' of null".

In the function googleLogin() there is a line that says "var next = getQueryString('next').replace(/^\s+|\s+$/g, '');" Because this line only passes in one parameter to getQueryString, getQueryString always returns null and the .replace() function always runs on a null variable, which breaks the code. 

I will look into this more/create a pull request if I have time, but it seems that the solution would be to add the url before calling getQueryString.

I also feel like this googleLogin function is unnecessarily long.  The googleLogin function for flask with stormpath looks like 

  function googleLogin() {
    window.location.replace('https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=/*client_id*/&scope=email+profile&include_granted_scopes=true&redirect_uri=/*redirect_uri*/');
  }

Why can't you make it just look like that?

**Comment by rdegges** [comment]
Ok, merged this in. Also added you to the contributors page: https://github.com/stormpath/stormpath-express/commit/8b7eadb04507caf69e57d0b5cc46c97e5a8778f1
