### ISSUE TITLE
Better error handling for humans

### ISSUE THREAD

**Issue by lemieux** [stormpath/stormpath-express#28]
Currently, express-stormpath outputs raw error pages when something happens. From what I can see, it's output a lot of `res.send(400)` or `res.send(500)` on "human facing" pages. I can understand for an API route, but for a page that a user can see, having a `400 Bad request` is less than desired.

My take on this would be to add a template for errors and use it to render them properly.

We saw this when accessing an account verification link twice, which is not really an edge case. In this case, it could also be useful to having the error message to let the user know what is going on.

Do you already have plans for this problem or should I go ahead and try to fix this?

**Comment by robertjd** [comment]
Bump this - a lot of useful error information (such as when an account store is disabled) is simply being rendered as an "Oops" message

**Comment by rdegges** [comment]
OK. I have an idea for this.

I'm thinking about creating an event emitter for error handling.

EG:

app.on('failedAPIAuthenticationAttempt', function(req, res, next) {
  ...
});

app.on('failedWebAuthenticationAttempt', function(req, res, next) {
  ...
});

etc

What do you think?

**Comment by robertjd** [comment]
This was fixed a long time ago, the library is now directly passing errors that come from the Stormpath API.
