### ISSUE TITLE
Create Account - Confirm Password

### ISSUE THREAD

**Issue by goldnmean** [stormpath/stormpath-express#35]
I need an option of being able to add a Confirm Password field beneath the Password field on the default Create Account form.  This Confirm Password field exists on the Create Account form in the Admin Console.

**Comment by rdegges** [comment]
I'll get this into the library soon =) Thanks all for the feature votes! I was initially against this <3

**Comment by rdegges** [comment]
This is officially available now. You can use the new `enableConfirmPassword` and `requireConfirmPassword` settings to enable this functionality!

**Comment by sholladay** [comment]
This is great, thanks @rdegges !

**Comment by alexwainger** [comment]
@rdegges Could you update the documentation here: https://docs.stormpath.com/java/spring-boot-web/registration.html#form-fields

This is a great add, but i'm not totally sure how to go about using it.

**Comment by markzero** [comment]
This functionality is removed now?

**Comment by robertjd** [comment]
Doh!  You're totally right, this got lost in the 2.x upgrade.  I've created #257 to track this.  I'll try to prio this, can you let me know if this is blocking you?  Thanks.

**Comment by markzero** [comment]
I continued without password repeat, maybe won't need it after all, but would be nice to have it as it's very common.
