### ISSUE TITLE
Resend verification page

### ISSUE THREAD

**Issue by lemieux** [stormpath/stormpath-express#37]
We were wondering what would happen if one of our users lost, deleted, forgot the verification email. Do you have plan to have a resend verification page or something like that? Currently it seems like the user would be in some sort of limbo state where he can't reset his password nor signup with the same email.

**Comment by rdegges** [comment]
So I just implemented this in the development branch. Going to finish cleaning it up and push a new release tomorrow with this included by default. The way it'll work is pretty simple:

On the login page you'll see a new link (like forgot password?) for resending your verification email if you have account verification enabled.

**Comment by rdegges** [comment]
Ok, this feature is now fully merged in and released. If you upgrade to the new **0.6.6** release this will be automatically turned on if you have `enableAccountVerification: true` in your settings.
