### ISSUE TITLE
App crashes with 404 shortly after initialization

### ISSUE THREAD

**Issue by holic** [stormpath/stormpath-express#48]
I'm initializing my Express app using the suggested env variables and the following code:

```js
// Attach Stormpath
app.use(stormpath.init(app, {
	secretKey: ''
}))
```

However, shortly after I start my app, I get a hard crash with only the following error:

```
ResourceError: HTTP 404, Stormpath 404 (mailto:support@stormpath.com): The requested resource does not exist.
```

I'm not really sure how to debug this...there are no other details provided by the error/crash.

**Comment by robertjd** [comment]
Can you verify the HREF that you're passing as STORMPATH_APPLICATION ?

It sounds like it can't find the application that is identified by that href.

**Comment by rdegges** [comment]
Heyo @holic I just pushed some experimental logging stuff into the develop branch of this library. I'm working on this more now. It should make things like this a bit easier to debug in the future.

Anyhow: if you're still having issues with this, please hit us up via support@stormpath.com -- the issue you're seeing means that the app href you defined isn't valid for some reason and the app can't be found via the api service.

**Comment by holic** [comment]
I dug around a bit in the code and saw that Stormpath defaults to a few different env variables, so I've updated the issue to reflect the new initialization code. Here's what the env vars look like:

```
STORMPATH_API_KEY_ID=
STORMPATH_API_KEY_SECRET=
STORMPATH_URL=https://api.stormpath.com/v1/applications/ID2Pd1noWfioAUrrJg2OP4UJ
```

**Comment by rdegges** [comment]
Can you email your full code to support@stormpath.com so I can take a look at it?

**Comment by rdegges** [comment]
Hey @holic, just closing this one out since we got it fixed. For the record, was just a misconfiged app href.

On a related note, however, I just pushed a new release, 0.6.1, which makes these errors all sorts of awesome -- and easier to debug =)
