### ISSUE TITLE
Can't turn off the requirement for givenName on register

### ISSUE THREAD

**Issue by bobbycircle** [stormpath/stormpath-express#50]
Maybe I'm doing something really dumb, but I've spent some time banging my head against this and can't get it to work.

I'm trying to present a reg form that requires simply Username, Email, and Password. But when I try and register, the form comes back with the alert, "Account givenName cannot be null, empty, or blank."

In my code I have:
```javascript
app.use(stormPath.init(app, {
    // ...
    enableUsername: true,
    requireUsername: true,
    enableGivenName: false,
    requireGivenName: false,
    enableSurname: false,
    requireSurname: false,
    // ...
}));
```
I've added some debug output to the `helpers.collectFormErrors` function but that doesn't seem to be where the alert is coming from. It's almost as if the validation is failing over at the stormpath server.

Thanks for any advice!
bobby

**Comment by robertjd** [comment]
Arg!  Let's see if we can figure this out.  Are you using the default login page, or a custom one?

**Comment by rdegges** [comment]
Working on this now. This is a confirmed bug =)

**Comment by rdegges** [comment]
Going to start by adding a test for the registration controller to assert these guys. Right now there are no controller tests yet, so might take a little bit.

**Comment by rdegges** [comment]
Bam, this is now fixed and released.
