### ISSUE TITLE
Unverified user receives ambiguous error message when logging in

### ISSUE THREAD

**Issue by richfoxton** [stormpath/stormpath-express#54]
If using email verification, when attempting to login as an unverified user (with correct credentials) the standard error message is returned...'Invalid username or password.'

It would be much better if a message reminding the user that they need to verify their email was displayed.

Thanks!

**Comment by rdegges** [comment]
Great find! I'll get this in there today.

**Comment by sholladay** [comment]
Did this ever get fixed? @rdegges

**Comment by robertjd** [comment]
Please re-open if this is still a problem with the new 2.x release
