### ISSUE TITLE
Allow init to accept an already configured cache client

### ISSUE THREAD

**Issue by TomDunn** [stormpath/stormpath-express#57]
First off, I've really enjoyed using Stormpath so far. Great work!

I'm looking to enable caching for my app. I see that the [product guide](http://docs.stormpath.com/nodejs/express/product.html#enable-caching) describes how you can tell stormpath what the host, port, and auth options are for the cache and then it makes its own connection to the cache.

Why not just accept an already configured cache client as well? I ask because in my app I have several other components that depend on a redis client, so instead of creating a client for every component I create one client and inject it into every component that needs it. The connection details change depending on the stage of the app so by using injection I isolate the stage/connection details to the one part of my app that is responsible for creating the client.

I explained my use case, and I think in general this would provide value for other users as well. What are your thoughts? I'd be willing to submit a PR if you like this idea.

Thanks again!

**Comment by robertjd** [comment]
I agree!  The underlying Node SDK does support this, see the docs here and note the `client` option:

http://docs.stormpath.com/nodejs/api/client#redis

For a PR, I think we need to pass that option here:

https://github.com/stormpath/stormpath-express/blob/daaf31023043e5077b167566faf5740a0cb8345a/lib/stormpath.js#L39

**Comment by TomDunn** [comment]
Thanks! Change seems straightforward enough, any suggestions for testing?

**Comment by TomDunn** [comment]
Actually, it looks like there is already a request in progress for this same feature:
https://github.com/stormpath/stormpath-express/pull/56 

Diff shows a change almost identical to what I made.

**Comment by rdegges** [comment]
Thanks everyone for commenting on this -- and sorry for my slow turnaround time.

I'm going to be merging the PR #56 into the library, and this is most definitely a needed / useful option.

I really appreciate ya'll bringing this to my attention <333

I'll leave another comment here once the PR has been merged, and a new release has been cut.

**Comment by rdegges** [comment]
Bam, new release has been cut! If you fetch 1.0.2 you'll be able to specify the `cacheClient` option when setting up the middleware =)
