### ISSUE TITLE
`authenticationRequired` middleware loses query parameters of original URL

### ISSUE THREAD

**Issue by jeffkole** [stormpath/stormpath-express#59]
On [line 180 of authentication.js](https://github.com/stormpath/stormpath-express/blob/master/lib/authentication.js#L180), the query parameters are explicitly stripped off from the URL before redirecting to the login page.

```
var url = req.app.get('stormpathLoginUrl') + '?next=' + encodeURIComponent(req.originalUrl.split('?')[0]);
```

This means that if you navigate to a page with query parameters and are redirected to login, you will not arrive back at the original page once you complete login.  It looks intentional though.  What was the rationale?

**Comment by rdegges** [comment]
Hey Jeff,

Good question. When I initially wrote this I didn't actually consider that at all -- I was just appending the next query param.

I'm 100% open to a PR to support maintaining query strings. I don't see any issue in getting that functionality into the library.

+1

**Comment by rdegges** [comment]
Closing this out as everything is merged in!
