### ISSUE TITLE
Wrong session duration in docs

### ISSUE THREAD

**Issue by ppitonak** [stormpath/stormpath-express#62]
Documentation says that by default, session expires after one month but in fact, it expires after 30 minutes
> By default, sessions will not expire for one month (out of convenience).

Code which defines default value:
https://github.com/stormpath/stormpath-express/blob/1.0.3/lib/settings.js#L60
```javascript
app.set('stormpathSessionDuration', opts.sessionDuration || parseInt(process.env.STORMPATH_SESSION_DURATION) || 1000 * 60 * 30);
```

**Comment by rdegges** [comment]
Thanks, you're 100% right, I'll fix this now =)

**Comment by rdegges** [comment]
Merged this in, closing.
