### ISSUE TITLE
Handle CSRF Expiration Errors in a Cleaner Way

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-express#63]
Right now, if a user opens up a page (login / registration), waits for a bit (for their session to expire), then submits the form -- they'll receive a CSRF error page.

This is quite ugly, and instead we should override this functionality with a custom flashed message of some sort, and re-render the page the user was on.

**Comment by bendpx** [comment]
Any updates guys?

**Comment by rdegges** [comment]
Gah, still haven't gotten to this yet, sorry >< I'll try to work on this first thing tomorrow morning. I've got some time dedicated to this project then.

**Comment by orpx** [comment]
+1

**Comment by rdegges** [comment]
Also: we'd like to emit an event when the CSRF token expires so a developer can respond to it.

**Comment by rdegges** [comment]
So, in the latest release of our express stuff, we no longer validate CSRF tokens for login / registration pages as they aren't useful here.

I'm closing this out as this is no longer an issue in the library.

**Comment by mdeggies** [comment]
Hey @rdegges, do you know if this still the case in express-stormpath? Looks like a CSRF token is being set on POST's to /login and /register.

**Comment by mdeggies** [comment]
Just to give everyone an update, CSRF protection is not offered in express-stormpath at the moment. To eliminate security issues in the future, we're going to work on making sure that the /login and /register endpoints accept only json (so in the event of CSRF attacks, CORS errors will be thrown).
