### ISSUE TITLE
Angular SDK Integration

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-express#64]
We should make this work with our Angular.js SDK by modifying the way sessions work: we should switch from storing a plain-old user href as the session cookie to storing a JWT.

**Comment by robertjd** [comment]
Agreed!  We also need to re-define some endpoints to serve HTML vs. JSON responses, and standardize request and response structures.  We're actually working on this ATM, we want to bring all our frameworks inline with the same spec so that Angular will work with all of them :)

**Comment by robertjd** [comment]
This is resolved.  This library is now issuing access tokens, via the the /oauth endpoint of the configured Stormpath Application.
