### ISSUE TITLE
LinkedIn support in Express-Stormpath 

### ISSUE THREAD

**Issue by terchris** [stormpath/stormpath-express#65]
Hi
I'm planning a site for health data and I would like to store the users in a secure system like stormpath.

When I read on your site and search the net I see that linkedIn support is mentioned. But I can't find if it is something that is planned or something that is there.

Regards
Terje

**Comment by rdegges** [comment]
Hey Terje,

This is something that our core API supports, but is not yet supported in this library directly. I'll have to work on getting that added in for ya.

-R

**Comment by thprapav** [comment]
+1 for this. Would like to be able to use this functionality soon.

**Comment by rdegges** [comment]
Quick update: we've been working on a new config format for this library which is almost complete. Once this major release has been made, we'll work on adding in a lot of the feature requests from the tracker here. We didn't forget about this, promise!

**Comment by rdegges** [comment]
Closing this as we are just merging this in.
