### ISSUE TITLE
Alternative Template Engines

### ISSUE THREAD

**Issue by coreybutler** [stormpath/stormpath-express#67]
Is it actually possible to specify a templating engine other than jade? 

The [docs](https://docs.stormpath.com/nodejs/express/product.html#using-ejs) indicate EJS support, but I couldn't get this to work as documented. It looks like [Jade is a hard dependency](https://github.com/stormpath/stormpath-express/blob/master/package.json#L29).

Frankly, I don't want to use Jade or EJS... my engine of choice is Nunjucks. Any thoughts on making this happen?

**Comment by luyizhao** [comment]
@coreybutler , you can define a custom renderHandler and set it to use Nunjucks when you initialize stormpath. Something like this:

```js
var renderHandler = function(view, res, options) {
  nunjucks.render(view, options, function(err, html) {
    if (err) {
      res.app.get('stormpathLogger').error('Couldn\'t render view (' + view + ') with options (' + options + ').');
      throw err;
    }
    res.send(html);
  })
};

app.use(stormpath.init(app, {
  renderHandler: renderHandler,
}));
```

**Comment by rdegges** [comment]
In our new 2.x release, this is a lottt easier. We allow you to use whatever views you want, and will respect your existing rendering options. This is explained here: http://docs.stormpath.com/nodejs/express/latest/templates.html

Going to close this out as it is now included in 2.x.
