### ISSUE TITLE
postRegistrationHandler not called when enableAccountVerification is set

### ISSUE THREAD

**Issue by adarqui** [stormpath/stormpath-express#68]
Hi everyone,

What's the best way to go about performing logic when an account is registered, with email verification enabled?

Regarding this "issue":
- Last commit: a4c685667ea40c1d62f6b3a0502c155fec326870
- Branch: master

In lib/controllers.js there is the following block starting on line 162:

```
        // If we get here, it means the account was successfully created.
        if (!err && !req.app.get('stormpathEnableAccountVerification')) { <--------------------- HERE
          if (req.app.get('stormpathPostRegistrationHandler')) {
            req.app.get('stormpathPostRegistrationHandler')(req.user, req, res, function() {
              var url = req.query.next || req.app.get('stormpathRedirectUrl');
              res.redirect(302, url);
            });
          } else {
            var url = req.query.next || req.app.get('stormpathRedirectUrl');
            res.redirect(302, url);
          }
        }
```

I could do it on Login, but it's a bit more messy. I'll do that if I have to, just wondering if there is a better way (or this creates a potential solution).

Thanks alot!

-- adarqui

**Comment by adarqui** [comment]
Just noticed this might already be in there. For some reason though it's never getting triggered when the user verifies their email.

lib/controllers.js line 521:

```
              if (req.app.get('stormpathPostRegistrationHandler')) {
                req.app.get('stormpathPostRegistrationHandler')(req.user, req, res, function() {
                  helpers.render(req.app.get('stormpathAccountVerificationCompleteView'), res);
                });
              } else {
                helpers.render(req.app.get('stormpathAccountVerificationCompleteView'), res);
              }
```

I'm developing something internally, so maybe that's why it's not able to trigger the handler:

    router.get(app.get('stormpathAccountVerificationCompleteUrl'), controllers.verificationComplete);

ah yes.. ok i've talked myself through an issue.

8|

closing.

**Comment by rdegges** [comment]
Glad it's working =)
