### ISSUE TITLE
Improve situation: Stormpath Application not ready

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-express#71]
If you hit an endpoint that requires the Stormpath application, and it has not yet been fetched from the a API, you'll git a bad reference exception.

We want to make two improvements:

* Have an async getter (promise?) for the application reference, and send down a 500 error if the reference isn't available yet
* Provide an `.on('ready')` type of handler that a user can use, if they want to wait for stormpath to be ready before they bootstrap their server

**Comment by andrhahn** [comment]
+1 on this.  My supertest tests fail because my server starts up and requests are sent before the stormpath.init is complete.

**Comment by rdegges** [comment]
@robertjd and I have a solution for this which we will be working on in the near future. Right now we're working on cutting a new release with some new config options / etc., so once the dust has settled with that we'll be fixing bugs.

**Comment by maceip** [comment]
+1

**Comment by rdegges** [comment]
Working on this now. Will update the issue as I make progress.

**Comment by rdegges** [comment]
You can now do this via the Express application object!

Here's how it works:

```javascript
var app = express();

app.use(stormpath.init(...));

app.on('stormpath.ready', function() {
  console.log('Stormpath is ready to go!');
  app.listen(3000);
});
```
Doing things this way ensures your web server ONLY starts after Stormpath is 100% initialized.

**Comment by rdegges** [comment]
Currently updating the docs to show this in the examples =) This will ensure users don't run into this anymore.

**Comment by rdegges** [comment]
Also throwing in some unit tests to assert this behavior.

**Comment by rdegges** [comment]
Closing this via https://github.com/stormpath/stormpath-express/pull/88
