### ISSUE TITLE
oauth2 grant scopes

### ISSUE THREAD

**Issue by ksmithut** [stormpath/stormpath-express#73]
Just a quick question (I hope), but does stormpath-express support oauth2.0 scopes? Or is this accomplished through stormpath groups?

**Comment by rdegges** [comment]
Right now this library doesn't expose any Oauth2 scope stuff. We're working on this right now.

The goal is to allow users to provide their own scoping mechanisms, or default to using groups.

**Comment by ksmithut** [comment]
ya, I guess it wouldn't be difficult to have build my own way of scoping out endpoints without the need to have this module provide that mechanism. Thanks :)
