### ISSUE TITLE
customData isn't being updated

### ISSUE THREAD

**Issue by erbridge** [stormpath/stormpath-express#74]
I'm setting some values on the customData, saving the user, then requesting them from a different route, and I'm getting the pre saved version. If I set the TTL to 1ms, it works fine.

I would expect the in memory cache to get updated immediately.

**Comment by rdegges** [comment]
Can you share the code you're using to reproduce this? I'll try to get it fixed.

**Comment by erbridge** [comment]
Here's a simplified example:

```js
var express = require('express');
var stormpath = require('express-stormpath');

var router = express.Router();

router.get('/', stormpath.loginRequired, function(req, res) {
  console.log(req.user.customData);
  
  res.render('view');
});

router.post('/start', stormpath.loginRequired, function(req, res) {
  var id = req.user.customData.currentId;

  if (id) {
    res.redirect(req.baseUrl);
    return;
  }

  if (!req.user.customData.objects) {
    req.user.customData.objects = {};
  }

  // TODO: Can we rely on these being unique?
  id = uuid.v4();

  req.user.customData.objects[id] = {
    startDate: new Date().toJSON(),
  };
  req.user.customData.currentId = id;

  req.user.save(function() {
    res.redirect(req.baseUrl);
  });
});

router.post('/stop', stormpath.loginRequired, function(req, res) {
  var id = req.user.customData.currentId;

  if (!id) {
    res.redirect(req.baseUrl);
    return;
  }

  req.user.customData.objects[id].endDate = new Date().toJSON();
  req.user.customData.remove('currentId');

  req.user.save(function() {
    res.redirect(req.baseUrl);
  });
});

module.exports = router;
```

The view just has buttons that post to `/start` and `/stop`

**Comment by rdegges** [comment]
Can you please try replacing:

```javascript
req.user.save(...);
```

With:

```javascript
req.user.customData.save(...);
```

In your code sample?

We've got a known bug in our underlying Node SDK which is affected by this: https://github.com/stormpath/stormpath-sdk-node/issues/161

Basically -- if you modify custom data, you need to call `req.user.customData.save()` to actually persist your changes AND update the cache. Simply calling `req.user.save()` will ONLY update your data, but won't update the cache.

We're working to get that fixed currently.

**Comment by rdegges** [comment]
To be clear: can you give that a try and let me know if it fixes your issue temporarily?

**Comment by erbridge** [comment]
Yes, that solves the issue, thanks. You might want to add documentation for that method exists. I'd prefer it to saving the entire user anyway.

**Comment by rdegges** [comment]
Will do!

**Comment by aghorpade** [comment]
We also faced same issue. Yes, but user.getCustomData.save() code change saved us. Thanks for this information here.
