### ISSUE TITLE
Don't rely on HOME Being Set

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-express#78]
https://github.com/stormpath/stormpath-express/blob/master/lib/settings.js#L222

We had a customer who was using this library on aws opsworks, and because HOME wasn't set, it was crashing. Took a lot of debugging, but it was because of this :(

**Comment by lhazlewood** [comment]
This is just a default algorithm - it should check $HOME/.stormpath/apiKey.properties as part of the api key resolution heuristics.  If $HOME isn't set, it is expected that the user configures the exact file path themselves, so I don't see what the issue is here.

**Comment by lhazlewood** [comment]
@rdegges for example, read the numbered list (1-5) here:

http://docs.stormpath.com/java/apidocs/com/stormpath/sdk/api/ApiKeyBuilder.html

These are the API Key resolution heuristics for the Java SDK.  If not available in one of these locations, the user *must* configure the API Key path (or raw values - not recommended) explicitly.

**Comment by rdegges** [comment]
Closing this as this logic is now a part of our Node SDK.
