### ISSUE TITLE
customData overwrites the object in the cache after save

### ISSUE THREAD

**Issue by xtu** [stormpath/stormpath-express#85]
In the postLoginHandler, I tried to update a custom field (let's say Field A) based on the value of another field (Field B). I do it like this way:
```javascript
postLoginHandler: function(account, req, res, next) {
    req.user.getCustomData(function(err, customData) {
      if (!err) {
        req.user.customData.FieldA = customData.FieldB;
        req.user.customData.save();
      }
    });
    next();
  }
```
Because in postLoginHandler, customData is not expanded, I have to expand it manually by calling getCustomData. After updating the Field A and calling account.customData.save() method to save it, in another following router, I called getCustomData again to try to fetch all custom data to do some other stuff. This time, I will only get the field I have updated (which is Field A) in the returned customData. All other custom fields disappear.

I believe it is caused when I call account.customData.save() method, the customData with partial data is saved to the cache and overwrites the object in cache.

I have found a way to avoid this issue by assigning the returned customData in the first call to the getCustomData method to req.user.customData so that it contains the full set of the custom data. 

```javascript
postLoginHandler: function(account, req, res, next) {
    req.user.getCustomData(function(err, customData) {
      if (!err) {
        // ADD THIS LINE TO AVOID PARTIAL CUSTOM DATA
        req.user.customData = customData;
        req.user.customData.FieldA = customData.FieldB;
        req.user.customData.save();
      }
    });
    next();
  }
```

**Comment by rdegges** [comment]
This is the desired behavior. When you call .getCustomData -- it returns the customData object (fresh) as a callback parameter -- it doesn't update the underlying object which made the call (it can't track those sorta memory references).

The way you should use it is to treat customData as it's own object, eg:

```javascript
req.user.getCustomData(function(err, data) {
  data.blah = 'blah';
  data.save(function(err) {
    req.user.customData = data;
    next();
  });
});
```

This is a fairly common pattern.

Sorry for the delay, just getting to this.
