### ISSUE TITLE
Bug: Unauthorized Access Attempt Crashes App

### ISSUE THREAD

**Issue by baer** [stormpath/stormpath-express#86]
This view comes back as undefined and crashes the app: https://github.com/stormpath/stormpath-express/blob/ec77ebee48a4cc790856b08dd6e9e8ef15bb120a/lib/authentication.js#L59

```js
  app.use(stormpath.init(app, {
    website: true,
    client: {
      apiKey: {
        id: config.stormpath.id,
        secret: config.stormpath.secret
      }
    },
    application: {
      href: config.stormpath.url
    }
  }));
```

```js
  app.get('/', stormpath.groupsRequired(['employee']), function(req, res) {
    res.sendFile('app.html', {root: config.root});
  });
```
stompath-express#2.0.1
node 0.12.7

**Comment by rdegges** [comment]
Working on this now.

**Comment by baer** [comment]
Thanks @rdegges!

**Comment by rdegges** [comment]
Got stuck writing tests for this on Friday -- continuing where I left off now =)

My new strategy with issues here is to first:

- Write full integration tests to reproduce.
- Fix bugs.
- Pass all tests.
- Write / update all necessary docs.
- Submit PR to resolve.
- Cut release.

**Comment by baer** [comment]
I :heart: that phrase: "Got stuck writing tests." Thanks for looking into this! If I understood more about express middleware I'd try to just PR it myself :/

**Comment by rdegges** [comment]
Hah, well -- I've been trying to improve test coverage. My goal is to dramatically improve the quality of this library ASAP. So, having 100% coverage, ensuring all bugs are 100% squashed, etc. Takes a bit longer to fix stuff this way, but makes code wayy better ^^

**Comment by rdegges** [comment]
All these repos will soon be at 0 open issues / PRs >:)

**Comment by rdegges** [comment]
Ok, this is all fixed / good to go. There is still some work left to handle customizing the view, but I'm going to handle that as a separate github issue because it doesn't really make sense to include it in this. I'm cutting a new release with this fix included right now (2.0.3).

**Comment by rdegges** [comment]
Release cut!

**Comment by baer** [comment]
Awesome! As soon as registration works again (#87) I'mma pull this into my project!

:metal: :metal: :metal:
